global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'couchdb-prometheus-exporter-example'

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
  #    static_configs:
  #      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  #    static_configs:
  #      - targets: ['node-exporter:9100']

  - job_name: 'couchdb'
    static_configs:
      - labels:
          instance: couchdb01
        targets:
          - couchdbstats1:9984
      - labels:
          instance: couchdb02
        targets:
          - couchdbstats2:9984
